version: '3.3'
services:

  backend:
    image: rbychin/profinance:latest
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    depends_on:
      - backend