name: test-app for Pro Finance

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/checkout@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt
      - name: Tests with flake and FastApi
        run: |
          python -m flake8
          python -m pytest

  build_and_push_to_docker_hub:
    name: Push images to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checking repo
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push backend to docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/profinance:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build_push_images
    steps:
      - name: Set up Docker environment
        run: sudo chmod 666 /var/run/docker.sock

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.HOST_KEY }}
          script: |
            cd infra
            docker compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/profinance
            docker compose up -d